# Урок 2

## Матрицы и матричные операции. Часть 1

In [1]:
import numpy as np

In [2]:
def task_1_helper(shape_1: tuple, shape_2: tuple) -> None:
    '''написана уже после решения, чисто для проверки, и чтобы по сто раз не писать про строки и столбцы'''
    matrix_1 = np.random.sample((shape_1[0], shape_1[1]))
    matrix_2 = np.random.sample((shape_2[0], shape_2[1]))
    try:
        matrix_1.dot(matrix_2)
        print(f'Определено умножение А х В, размерность А х В: {(matrix_1.dot(matrix_2)).shape}')
    except:
        print(f'Умножение А х В не определено')
    try:
        matrix_2.dot(matrix_1)
        print(f'Определено умножение В х А, размерность В х А: {(matrix_2.dot(matrix_1)).shape}')
    except:
        print(f'Умножение В х А не определено')

Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

Произведения AB и ВА не определены, так как количество столбцов матрицы А не равно количеству строк матрицы В, а количество столбцов матрицы В не равно количеству строк матрицы А.

In [3]:
task_1_helper((4, 2), (4, 2))

Умножение А х В не определено
Умножение В х А не определено


   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

Определено произведение АВ, получится матрица 2 х 3:

In [4]:
task_1_helper((2, 5), (5, 3))

Определено умножение А х В, размерность А х В: (2, 3)
Умножение В х А не определено


   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

Определены и АВ и ВА, получатся матрицы 8 х 8 и 3 х 3 соответственно:

In [5]:
task_1_helper((8, 3), (3, 8))

Определено умножение А х В, размерность А х В: (8, 8)
Определено умножение В х А, размерность В х А: (3, 3)


   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Определены и АВ и ВА, получатся матрицы 4 х 4:

In [6]:
task_1_helper((4, 4), (4, 4))

Определено умножение А х В, размерность А х В: (4, 4)
Определено умножение В х А, размерность В х А: (4, 4)


__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



In [7]:
sum_a_b = np.array([1 + 4, -2 - 1, 3 + 0, 0 + 5]).reshape(2, 2)
sum_a_b

array([[ 5, -3],
       [ 3,  5]])

In [8]:
mul_a_b = np.array([1*4 + (-2)*0, 1*(-1) + (-2)*5, 3*4 + 0*0, 3*(-1) + 0*5]).reshape(2, -1)
mul_a_b

array([[  4, -11],
       [ 12,  -3]])

In [9]:
a = np.array([1, -2, 3, 0]).reshape(2, 2)
b = np.array([4, -1, 0, 5]).reshape(2, 2)
a.dot(b) == mul_a_b

array([[ True,  True],
       [ True,  True]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


In [10]:
lin_a_b_c = np.array([3*1 - 2*0 + 4*2, 3*7 - 2*5 + 4*(-4), 3*3 - 2*2 + 4*1, 3*(-6) - 2*(-1) + 4*1]).reshape(2, 2)
lin_a_b_c

array([[ 11,  -5],
       [  9, -12]])

In [11]:
a = np.array([1, 7, 3, -6]).reshape(2, 2)
b = np.array([0, 5, 2, -1]).reshape(2, 2)
c = np.array([2, -4, 1, 1]).reshape(2, 2)
3*a - 2*b + 4*c == lin_a_b_c

array([[ True,  True],
       [ True,  True]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.



Воспользуюсь функцией из 5 задачи

In [12]:
def my_mul(matrix_1: list, matrix_2: list) -> list:
    shape_1 = (len(matrix_1[0]), len(matrix_1))
    shape_2 = (len(matrix_2[0]), len(matrix_2))
    if shape_1[1] != shape_2[0]:
        raise ValueError(f'Не совпадает количество столбцов 1 матрицы ({shape_1[1]})\
        и количество столбцов 2 матрицы ({shape_2[0]})')
    res = [[sum(ele_1*ele_2 for ele_1, ele_2 in zip(row_1, col_2)) \
            for col_2 in zip(*matrix_2)] for row_1 in matrix_1]
    return res


In [13]:
a = np.array([4, 1, 5, -2, 2, 3]).reshape(3, 2)
a_at = np.array(my_mul(a, a.T))
a_at

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [14]:
a_at == a.dot(a.T)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
at_a = np.array(my_mul(a.T, a))
at_a

array([[45,  0],
       [ 0, 14]])

In [16]:
at_a == a.T.dot(a)

array([[ True,  True],
       [ True,  True]])

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

В прошлом задании.

# Матрицы и матричные операции. Часть 2

## Практическое задание

Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$






det_a = (sin x)^2 + (cos x)^2 = 1

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    


In [17]:
det_b = 4 * 5 * 9
det_b

180

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [18]:
det_c = 1 * (5*9 - 6*8) - 2 * (4*9 - 7*6) + 3 * (4*8 - 5*7)
det_c

0

In [19]:
c = np.array([list(range(1, 10))]).reshape(3, 3)
np.linalg.det(c)

0.0

__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
  

det(A х A) = det(A) * det(A) = 16

 б) $det(A^{T})$;
    

   


det(A.T) = det(A) = 4

   в) $det(2A)$.

Чтобы привести определитель матрицы 2 х А к определителю матрицы А, нужно из каждой строчки вынести коэффициент (двойку). То есть, всего n раз, где n - число строк матрицы А.
В таком случае, det(2A) = 2^n х det(A) = 2^(n + 2)

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



Матрица называется _сингулярной_ или _вырожденной_, если её определитель равен нулю.

In [20]:
det_a = np.linalg.det(np.array([-2, 7, -3, 4, -14, 6, -3, 7, 13]).reshape(3, 3))
det_a

0.0

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$



Третья строка матрицы это сумма первых двух строк, поэтому ее можно отбросить. Остальные строки/столбцы линейно независимы. Значит, ранг матрицы равен 2

In [21]:
a = np.array([1, 2, 3, 1, 1, 1, 2, 3, 4]).reshape(3, 3)
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Опять, третья строка это сумма первых двух. Выбрасываем. Второй столбец равен первому, умноженному на 1.5.
Выбрасываем тоже. Остальные строки/столбцы линейно независимы. Значит, ранг матрицы равен 3

In [22]:
b = np.array([0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 4, 3, 2, 3, 5, 6]).reshape(4, 4)
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
