# Урок 5

# Сингулярное разложение матриц

## Практическое задание

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$




In [1]:
import numpy as np

In [3]:
A = np.array([1, 2, 0, 0, 0, 5, 3, -4, 2, 1, 6, 5, 0, 1, 0]).reshape(5, -1)
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [7]:
U, s, W = np.linalg.svd(A)
V = W.T

In [8]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [9]:
display(U, D, V)

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

array([[ 0.07116451, -0.36737824, -0.92734505],
       [ 0.71702467,  0.66514082, -0.20847855],
       [ 0.69340553, -0.65009301,  0.31075368]])

Проверка:

In [10]:
np.dot(np.dot(U, D), V.T)

array([[ 1.00000000e+00,  2.00000000e+00,  1.31018987e-15],
       [ 1.93009612e-16, -2.66609409e-15,  5.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  5.00000000e+00],
       [-5.49534701e-17,  1.00000000e+00, -3.02821608e-17]])

2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;


In [12]:
mu = np.max(D)
mu

8.824868854820444

    
    б) норму Фробениуса.

In [15]:
np.linalg.norm(A, ord=None)

11.045361017187261

Проверка:


In [18]:
sum([D[i][i]**2 for i in range(3)])**(1/2)

11.045361017187263